### ISSUE TITLE
New WooCommerce products not synchronized

### ISSUE THREAD

**Issue by DanielBakovic** [ThemeAvenue/Awesome-Support#122]
Hi,
I have an issues with the plugin. After the plugin activation my WooCommerce products have been added to Ticktes -> Products but products added after Awesome-Support activation are not available on the Ticktes ->Products page.

How can I trigger the synchronisation again?

**Comment by julien731** [comment]
Products should be automatically synchronized every time you go to *Tickets > Products*. If it's not the case then there must be a problem somewhere. Do you see any PHP error or anything that's not supposed to be displayed?

**Comment by DanielBakovic** [comment]
There no errors, notices or warning in  the debug.log.

Currently I have 3 products in WooCommerce but only one ist displayed on Ticktes -> Products.

**Comment by SiamKreative** [comment]
Bump! @bryceadams

**Comment by mripa** [comment]
any updates on this? i have a very similar issue.. only about 3rd of the products are syncing up from woocomerce to the ticketing system

**Comment by DanielBakovic** [comment]
With this issues the plugin isn't usable with WooCommerce. Could you please fix it?

**Comment by julien731** [comment]
Could you guys specify which version of WooCommerce you're running.

**Comment by DanielBakovic** [comment]
The latest one

**Comment by DanielBakovic** [comment]
any news on this?

**Comment by julien731** [comment]
I'm testing it with Awesome Support 3.1.6 and WooCommerce 2.3.8 and everything works fine. Myabe this is related to your particular install. Could you please paste your system status report here (*Tickets > System Status > Copy Report*).

**Comment by DanielBakovic** [comment]
Hi,

here are our details:

WordPress
WP Version  4.2.1
WP Multisite  No
WP Language en_US
WP Debug Mode Yes
WP Active Plugins 4
WP Max Upload Size  8 MB
WP Memory Limit 128M
WP Timezone The timezone hasn't been set

Server
PHP Version 5.5.11
Software  Apache/2.4.9 (Win32) OpenSSL/1.0.1g PHP/5.5.11

Settings
Version 3.1.6
DB Version  1
Tickets Slug  ticket
Products Slug product
Multiple Products Enabled

Plugins Installed
Awesome Support by ThemeAvenue version 3.1.6,
WPBakery Visual Composer by Michael M - WPBakery.com version 4.4.2,
Revolution Slider by ThemePunch version 4.6.5,
WooCommerce by WooThemes version 2.3.8,

Currently there are 27 WooCommerce products but only 10 are displayed by Awesome Support

**Comment by DanielBakovic** [comment]
Today we tried Awesome Support on our second Woocommerce site with 57 products. The plugin displays only 20 products! This is anything than "Awesome" :(

**Comment by DanielBakovic** [comment]
Hi,
here is an instruction how to reproduce the issue:

1. Install WordPress and WooCommerce
2. Import this ZIP file with 23 WooCommerce products (WooCommerce must be enabled): https://www.dropbox.com/s/hg855monkdq9ovj/wordpress.2015-05-04.zip?dl=0
3. Activate Awesome Support and check "Multiple Products"
4. Navigate to Tickets -> Products to check if all of the 23 items are available there.

I've attached two screenshots that show that only 10 products are visible on Tickets menu.

![support-products](https://cloud.githubusercontent.com/assets/1132636/7450369/55e64106-f244-11e4-9645-8e24f7ac9d5d.png)
![woocommerce-products](https://cloud.githubusercontent.com/assets/1132636/7450370/55ea72d0-f244-11e4-9c4c-066d8f8abec1.png)

Hope this will help you to reproduce the issue.

Best regards,
Daniel

**Comment by julien731** [comment]
Excellent thanks. I'll be testing this asap.

**Comment by SiamKreative** [comment]
Thanks @DanielBakovic ! I tried myself on an existing install, and I see a PHP notice and only a few items:
```
Notice: Trying to get property of non-object in C:\wamp\www\awesome-support\wp-includes\link-template.php on line 907
```

**Comment by julien731** [comment]
This issue should be fixed now. For already bugged installs, there is now a *Resync* button in *Tickets > System Status > Tools* that will clear the products and re-synchronize it properly.

**Comment by DanielBakovic** [comment]
Hi,

I don't see the button. It looks like the action 'wpas_system_tools_table_after' is never fired. I suppose the do_action is missing in this file: https://github.com/ThemeAvenue/Awesome-Support/blob/f8af40bd18386f0663f09e9f53be4a7bb134497f/includes/admin/views/system-tools.php

**Comment by julien731** [comment]
Are you using the dev version?

**Comment by DanielBakovic** [comment]
Yes, I pulled it from the git repo

**Comment by DanielBakovic** [comment]
Hi,
I see the button now. Maybe i pulled a wrong commit but the synchronization is still not working.

I imported the XML file that I've posted above and activated Awesome-Support plugin. I see only 13 of 23 products, even if I run the re-synchronization.

The debug log is full of messages:

<code>[05-May-2015 19:03:35 UTC] PHP Warning:  Illegal string offset 'term_id' in C:\xampp\htdocs\mysite\wp-content\plugins\awesome-support\includes\class-product-sync.php on line 624

[05-May-2015 19:03:35 UTC] PHP Stack trace:

[05-May-2015 19:03:35 UTC] PHP   1. {main}() C:\xampp\htdocs\mysite\wp-admin\edit.php:0

[05-May-2015 19:03:35 UTC] PHP   2. require_once() C:\xampp\htdocs\mysite\wp-admin\edit.php:10

[05-May-2015 19:03:35 UTC] PHP   3. do_action() C:\xampp\htdocs\mysite\wp-admin\admin.php:158

[05-May-2015 19:03:35 UTC] PHP   4. call_user_func_array() C:\xampp\htdocs\mysite\wp-includes\plugin.php:496

[05-May-2015 19:03:35 UTC] PHP   5. Awesome_Support_Admin->system_tools() C:\xampp\htdocs\mysite\wp-includes\plugin.php:496

[05-May-2015 19:03:35 UTC] PHP   6. wpas_delete_synced_products() C:\xampp\htdocs\mysite\wp-content\plugins\awesome-support\includes\admin\class-admin.php:1145

[05-May-2015 19:03:35 UTC] PHP   7. WPAS_Product_Sync->unsync_term() C:\xampp\htdocs\mysite\wp-content\plugins\awesome-support\includes\admin\functions-tools.php:146

[05-May-2015 19:03:35 UTC] PHP Notice:  Uninitialized string offset: 0 in C:\xampp\htdocs\mysite\wp-content\plugins\awesome-support\includes\class-product-sync.php on line 624

[05-May-2015 19:03:35 UTC] PHP Stack trace:

[05-May-2015 19:03:35 UTC] PHP   1. {main}() C:\xampp\htdocs\mysite\wp-admin\edit.php:0

[05-May-2015 19:03:35 UTC] PHP   2. require_once() C:\xampp\htdocs\mysite\wp-admin\edit.php:10

[05-May-2015 19:03:35 UTC] PHP   3. do_action() C:\xampp\htdocs\mysite\wp-admin\admin.php:158

[05-May-2015 19:03:35 UTC] PHP   4. call_user_func_array() C:\xampp\htdocs\mysite\wp-includes\plugin.php:496

[05-May-2015 19:03:35 UTC] PHP   5. Awesome_Support_Admin->system_tools() C:\xampp\htdocs\mysite\wp-includes\plugin.php:496

[05-May-2015 19:03:35 UTC] PHP   6. wpas_delete_synced_products() C:\xampp\htdocs\mysite\wp-content\plugins\awesome-support\includes\admin\class-admin.php:1145

[05-May-2015 19:03:35 UTC] PHP   7. WPAS_Product_Sync->unsync_term() C:\xampp\htdocs\mysite\wp-content\plugins\awesome-support\includes\admin\functions-tools.php:146</code>

**Comment by DanielBakovic** [comment]
Another interesting issue. At Products -> Tickes it says "13 items" but only 10 are displayed. There is no pagination and the "items per page" is set to 50.

**Comment by SiamKreative** [comment]
I'm re-opening this issue as it's still not working. Here's what I did:

* Try to resync the existing products (from previously imported XML). **It didn't work at all. I could see the same errors as before. Nothing changed**
* Try to delete products, then resync. This triggered new errors (see screenshot below).

![image](https://cloud.githubusercontent.com/assets/1778633/7559044/cbbdc5ee-f7d9-11e4-8d5c-ae1857b0e7aa.png)

**Comment by julien731** [comment]
There is still a bug with products synchronization, but at least the re-sync tool should be working with this modification.

**Comment by julien731** [comment]
OMG. I spent 2 days trying to understand some senseless post metas that were breaking the product synchronization only to realize this morning that the said post metas were imported by your XML file @DanielBakovic :(

The product synchronization does work correctly. There surely was a bug during the initial sync before but it was fixed the first time I closed this ticket.

I have done a couple of improvements anyways and the re-sync tool should clean in-depth the products and re-sync them nicely.

I'll close the ticket now and hopefully it won't need re-opening ;)

**Comment by DanielBakovic** [comment]
Hi Julien,

I'm really sorry but this is still not working correctly:

```
PHP Warning:  Illegal string offset 'term_id' in \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php on line 630

PHP Notice:  Uninitialized string offset: 0 in \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php on line 630

PHP Fatal error:  Maximum function nesting level of '100' reached, aborting! in \wp\wp-includes\functions.php on line 4777

PHP Stack trace:

PHP   1. {main}() \wp\wp-admin\edit.php:0

PHP   2. require_once() \wp\wp-admin\edit.php:10

PHP   3. do_action() \wp\wp-admin\admin.php:158

PHP   4. call_user_func_array() \wp\wp-includes\plugin.php:496

PHP   5. Awesome_Support_Admin->system_tools() \wp\wp-includes\plugin.php:496

PHP   6. wpas_delete_synced_products() \wp\wp-content\plugins\awesome-support\includes\admin\class-admin.php:1158

PHP   7. WPAS_Product_Sync->run_initial_sync() \wp\wp-content\plugins\awesome-support\includes\admin\functions-tools.php:175

PHP   8. WPAS_Product_Sync->create_term_object() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:832

PHP   9. WPAS_Product_Sync->insert_term() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:330

PHP  10. wp_insert_term() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:382

PHP  11. get_terms() \wp\wp-includes\taxonomy.php:2921

PHP  12. apply_filters() \wp\wp-includes\taxonomy.php:2060

PHP  13. call_user_func_array() \wp\wp-includes\plugin.php:213

PHP  14. WPAS_Product_Sync->get_terms() \wp\wp-includes\plugin.php:213

PHP  15. WPAS_Product_Sync->run_initial_sync() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:492

PHP  16. WPAS_Product_Sync->create_term_object() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:832

PHP  17. WPAS_Product_Sync->insert_term() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:330

PHP  18. wp_insert_term() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:382

PHP  19. get_terms() \wp\wp-includes\taxonomy.php:2921

PHP  20. apply_filters() \wp\wp-includes\taxonomy.php:1732

PHP  21. call_user_func_array() \wp\wp-includes\plugin.php:213

PHP  22. WPAS_Product_Sync->get_terms() \wp\wp-includes\plugin.php:213

PHP  23. WPAS_Product_Sync->run_initial_sync() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:492

PHP  24. WPAS_Product_Sync->create_term_object() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:832

PHP  25. WPAS_Product_Sync->insert_term() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:330

PHP  26. wp_insert_term() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:382

PHP  27. get_terms() \wp\wp-includes\taxonomy.php:2921

PHP  28. apply_filters() \wp\wp-includes\taxonomy.php:1732

PHP  29. call_user_func_array() \wp\wp-includes\plugin.php:213

PHP  30. WPAS_Product_Sync->get_terms() \wp\wp-includes\plugin.php:213

PHP  31. WPAS_Product_Sync->run_initial_sync() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:492

PHP  32. WPAS_Product_Sync->create_term_object() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:832

PHP  33. WPAS_Product_Sync->insert_term() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:330

PHP  34. wp_insert_term() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:382

PHP  35. get_terms() \wp\wp-includes\taxonomy.php:2921

PHP  36. apply_filters() \wp\wp-includes\taxonomy.php:1732

PHP  37. call_user_func_array() \wp\wp-includes\plugin.php:213

PHP  38. WPAS_Product_Sync->get_terms() \wp\wp-includes\plugin.php:213

PHP  39. WPAS_Product_Sync->run_initial_sync() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:492

PHP  40. WPAS_Product_Sync->create_term_object() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:832

PHP  41. WPAS_Product_Sync->insert_term() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:330

PHP  42. wp_insert_term() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:382

PHP  43. get_terms() \wp\wp-includes\taxonomy.php:2921

PHP  44. apply_filters() \wp\wp-includes\taxonomy.php:1732

PHP  45. call_user_func_array() \wp\wp-includes\plugin.php:213

PHP  46. WPAS_Product_Sync->get_terms() \wp\wp-includes\plugin.php:213

PHP  47. WPAS_Product_Sync->run_initial_sync() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:492

PHP  48. WPAS_Product_Sync->create_term_object() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:832

PHP  49. WPAS_Product_Sync->insert_term() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:330

PHP  50. wp_insert_term() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:382

PHP  51. get_terms() \wp\wp-includes\taxonomy.php:2921

PHP  52. apply_filters() \wp\wp-includes\taxonomy.php:1732

PHP  53. call_user_func_array() \wp\wp-includes\plugin.php:213

PHP  54. WPAS_Product_Sync->get_terms() \wp\wp-includes\plugin.php:213

PHP  55. WPAS_Product_Sync->run_initial_sync() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:492

PHP  56. WPAS_Product_Sync->create_term_object() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:832

PHP  57. WPAS_Product_Sync->insert_term() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:330

PHP  58. wp_insert_term() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:382

PHP  59. get_terms() \wp\wp-includes\taxonomy.php:2921

PHP  60. apply_filters() \wp\wp-includes\taxonomy.php:1732

PHP  61. call_user_func_array() \wp\wp-includes\plugin.php:213

PHP  62. WPAS_Product_Sync->get_terms() \wp\wp-includes\plugin.php:213

PHP  63. WPAS_Product_Sync->run_initial_sync() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:492

PHP  64. WPAS_Product_Sync->create_term_object() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:832

PHP  65. WPAS_Product_Sync->insert_term() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:330

PHP  66. wp_insert_term() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:382

PHP  67. clean_term_cache() \wp\wp-includes\taxonomy.php:3019

PHP  68. _get_term_hierarchy() \wp\wp-includes\taxonomy.php:3770

PHP  69. get_terms() \wp\wp-includes\taxonomy.php:3904

PHP  70. apply_filters() \wp\wp-includes\taxonomy.php:2060

PHP  71. call_user_func_array() \wp\wp-includes\plugin.php:213

PHP  72. WPAS_Product_Sync->get_terms() \wp\wp-includes\plugin.php:213

PHP  73. WPAS_Product_Sync->run_initial_sync() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:492

PHP  74. WPAS_Product_Sync->create_term_object() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:832

PHP  75. WPAS_Product_Sync->insert_term() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:330

PHP  76. wp_insert_term() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:382

PHP  77. clean_term_cache() \wp\wp-includes\taxonomy.php:3019

PHP  78. _get_term_hierarchy() \wp\wp-includes\taxonomy.php:3770

PHP  79. get_terms() \wp\wp-includes\taxonomy.php:3904

PHP  80. apply_filters() \wp\wp-includes\taxonomy.php:1732

PHP  81. call_user_func_array() \wp\wp-includes\plugin.php:213

PHP  82. WPAS_Product_Sync->get_terms() \wp\wp-includes\plugin.php:213

PHP  83. WPAS_Product_Sync->run_initial_sync() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:492

PHP  84. WPAS_Product_Sync->create_term_object() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:832

PHP  85. WPAS_Product_Sync->insert_term() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:330

PHP  86. wp_insert_term() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:382

PHP  87. clean_term_cache() \wp\wp-includes\taxonomy.php:3019

PHP  88. _get_term_hierarchy() \wp\wp-includes\taxonomy.php:3770

PHP  89. get_terms() \wp\wp-includes\taxonomy.php:3904

PHP  90. apply_filters() \wp\wp-includes\taxonomy.php:1732

PHP  91. call_user_func_array() \wp\wp-includes\plugin.php:213

PHP  92. WPAS_Product_Sync->get_terms() \wp\wp-includes\plugin.php:213

PHP  93. WPAS_Product_Sync->map_args() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:472

PHP  94. sanitize_title() \wp\wp-content\plugins\awesome-support\includes\class-product-sync.php:230

PHP  95. apply_filters() \wp\wp-includes\formatting.php:1276

PHP  96. call_user_func_array() \wp\wp-includes\plugin.php:213

PHP  97. sanitize_title_with_dashes() \wp\wp-includes\plugin.php:213

PHP  98. seems_utf8() \wp\wp-includes\formatting.php:1320

PHP  99. mbstring_binary_safe_encoding() \wp\wp-includes\formatting.php:593
```
