### ISSUE TITLE
Notifications not showing up

### ISSUE THREAD

**Issue by SiamKreative** [ThemeAvenue/Awesome-Support#63]
On three different local WordPress installs, the notifications (for instance "Password incorrect...") do no show up.

* WAMP 2.5
* Apache : 2.4.9
* MySQL : 5.6.17
* PHP : 5.5.12

Tested with both WordPress 4.0.1, WordPress 4.1 and WordPress 4.2-alpha-31181. Tried both the latest plugin from Github & Version 3.0.1 from WordPress.org.

Anyone else able to replicate the issue? What PHP version and/or extension is required for these notifications to appear?

**Comment by SiamKreative** [comment]
Here is the system report for version 4.1.

```json
[{
	"label": "wordpress",
	"data": [{
		"key": "Site URL",
		"value": "http://dev.com/awesome-support"
	}, {
		"key": "Home URL",
		"value": "http://dev.com/awesome-support"
	}, {
		"key": "WP Version",
		"value": "4.1"
	}, {
		"key": "WP Multisite",
		"value": "No"
	}, {
		"key": "WP Language",
		"value": "en_US"
	}, {
		"key": "WP Debug Mode",
		"value": "Yes"
	}, {
		"key": "WP Active Plugins",
		"value": "5"
	}, {
		"key": "WP Max Upload Size",
		"value": "32 MB"
	}, {
		"key": "WP Memory Limit",
		"value": "40M"
	}, {
		"key": "WP Timezone",
		"value": "The timezone hasn't been set"
	}]
}, {
	"label": "server",
	"data": [{
		"key": "PHP Version",
		"value": "5.5.12"
	}, {
		"key": "Software",
		"value": "Apache/2.4.9 (Win64) OpenSSL/1.0.1g PHP/5.5.12"
	}]
}, {
	"label": "settings",
	"data": [{
		"key": "Version",
		"value": "3.0.1"
	}, {
		"key": "DB Version",
		"value": "1"
	}, {
		"key": "Tickets Slug",
		"value": "ticket"
	}, {
		"key": "Products Slug",
		"value": "product"
	}, {
		"key": "Multiple Products",
		"value": "Disabled"
	}, {
		"key": "Registration Status",
		"value": "Open"
	}, {
		"key": "Registration Page",
		"value": "Default"
	}, {
		"key": "Uploads Folder",
		"value": "The upload folder exists and is writable"
	}, {
		"key": "Allowed File Types",
		"value": ".jpg, .jpeg, .png, .gif, .pdf, .doc, .docx, .ppt, .pptx, .pps, .ppsx, .odt, .xls, .xlsx, .mp3, .m4a, .ogg, .wav, .mp4, .m4v, .mov, .wmv, .avi, .mpg, .ogv, .3gp, .3g2, .zip"
	}, {
		"key": "WYSIWYG On Front",
		"value": "Yes"
	}]
}, {
	"label": "pages",
	"data": [{
		"key": "Ticket Submission",
		"value": "http://dev.com/awesome-support/submit-ticket/ (#5)"
	}, {
		"key": "Tickets List",
		"value": "http://dev.com/awesome-support/my-tickets/ (#4)"
	}]
}, {
	"label": "email-notifications",
	"data": [{
		"key": "Submission Confirmation",
		"value": "Enabled"
	}, {
		"key": "New Assignment",
		"value": "Enabled"
	}, {
		"key": "New Agent Reply",
		"value": "Enabled"
	}, {
		"key": "New Client Reply",
		"value": "Enabled"
	}, {
		"key": "Ticket Closed",
		"value": "Enabled"
	}]
}, {
	"label": "custom-fields",
	"data": [{
		"key": "Support Staff",
		"value": "Capability: create_ticket, Core: Yes, Required: No, Logged: Yes, Show Column: No, Taxonomy: No, Callback: text"
	}, {
		"key": "Status",
		"value": "Capability: create_ticket, Core: Yes, Required: No, Logged: No, Show Column: Yes, Taxonomy: No, Callback:"
	}, {
		"key": "Ticket Tag",
		"value": "Capability: create_ticket, Core: Yes, Required: No, Logged: Yes, Show Column: Yes, Taxonomy: Yes (standard), Callback: taxonomy"
	}]
}, {
	"label": "plugins",
	"data": [{
		"key": "Installed",
		"value": "Awesome Support by ThemeAvenue version 3.0.1, Debug Bar by wordpressdotorg version 0.8.2, P3 (Plugin Performance Profiler) by GoDaddy.com version 1.5.3.4, User Switching by John Blackbourn version 1.0.2, WooCommerce by WooThemes version 2.2.10"
	}]
}, {
	"label": "theme",
	"data": [{
		"key": "Theme Name:",
		"value": "Twenty Fifteen"
	}, {
		"key": "Theme Version:",
		"value": "1.0"
	}, {
		"key": "Theme Author URL:",
		"value": "https://wordpress.org/"
	}, {
		"key": "Is Child Theme:",
		"value": "No"
	}]
}, {
	"label": "templates",
	"data": [{
		"key": "Overrides:",
		"value": "There is no template override"
	}]
}]
```

**Comment by julien731** [comment]
The notifications system will be improved (see #28 ) and that should fix the issue.

**Comment by SiamKreative** [comment]
Notifications still don't show up using the latest dev version & WordPress 4.2.2. Tested on Chrome 42.0.2311.152 m (64-bit), Firefox 35.0, Vivaldi.

It doesn't work on many live sites too:
* [Our own support](http://getawesomesupport.com/submit-ticket/?message=IjxzdHJvbmc%2BRVJST1I8XC9zdHJvbmc%2BOiBJbnZhbGlkIHVzZXJuYW1lIG9yIGluY29ycmVjdCBwYXNzd29yZC4i).
* [75nineteen.com](http://www.75nineteen.com/submit-ticket/?message=IjxzdHJvbmc%2BRVJST1I8XC9zdHJvbmc%2BOiBJbnZhbGlkIHVzZXJuYW1lLiA8YSBocmVmPVwiaHR0cHM6XC9cL3d3dy43NW5pbmV0ZWVuLmNvbVwvbXktYWNjb3VudFwvbG9zdC1wYXNzd29yZFwvXCI%2BTG9zdCB5b3VyIHBhc3N3b3JkPzxcL2E%2BIg%3D%3D)
* [unitedchemicalcorp.com](https://support.unitedchemicalcorp.com/submit-ticket/?message=IjxzdHJvbmc%2BRVJST1I8XC9zdHJvbmc%2BOiBJbnZhbGlkIHVzZXJuYW1lLiA8YSBocmVmPVwiaHR0cHM6XC9cL3N1cHBvcnQudW5pdGVkY2hlbWljYWxjb3JwLmNvbVwvbXktYWNjb3VudFwvbG9zdC1wYXNzd29yZFwvXCI%2BTG9zdCB5b3VyIHBhc3N3b3JkPzxcL2E%2BIg%3D%3D)

**Comment by SiamKreative** [comment]
I applied the fixes 16ebb1b from @rudashi and tadam!
![image](https://cloud.githubusercontent.com/assets/1778633/7741392/7b365b82-ffa8-11e4-801a-d0a7e5f33adf.png)

**Comment by julien731** [comment]
Fixed in e0928810a81ed21679ff2c93a72fb36ca6f2fa5c
