### ISSUE TITLE
Duplicate "history" when when closing ticket

### ISSUE THREAD

**Issue by SiamKreative** [ThemeAvenue/Awesome-Support#99]
![wpas-close-issue](https://cloud.githubusercontent.com/assets/1778633/6476962/874a3830-c24f-11e4-971f-4b5c4030d2ec.png)

When using "Reply and close", the ticket history shows 2 actions instead of one.

**Comment by julien731** [comment]
This seems to have been fixed, most likely by e125f94870534c29ffd4ac969adfd40d62743c30

**Comment by SiamKreative** [comment]
Still not working with latest version (2b2c2f3415115b344db4791d82bb1e3f1af4ba47), WordPress Version 4.1.1 & WAMP 2.5

**Comment by julien731** [comment]
This seem to happen only when using the "Reply & Close" button.
